home:
    path:     /
    defaults: { _controller: PersonalBundle:Default:index }

projects:
    path:   /projects
    defaults: { _controller: PersonalBundle:Default:projects }
    
game:
    path:   /game
    defaults: { _controller: PersonalBundle:Default:game }

gmail:
    path:   /gmail
    defaults: { _controller: PersonalBundle:Default:gmail }
    
facebook:
    path:   /example
    defaults: { _controller: PersonalBundle:Default:facebook }
    
menu:
    path:   /menu
    defaults: { _controller: PersonalBundle:Default:menu }

privacy:
    path:   /privacy
    defaults: { _controller: PersonalBundle:Default:privacy }

media:
    path:   /media
    defaults: { _controller: PersonalBundle:Default:media }
    
shitpost:
    path:   /shitpost
    defaults: { _controller: PersonalBundle:Default:shitpost }
