home:
    path:     /
    defaults: { _controller: PersonalBundle:Default:index }

projects:
    path:   /projects
    defaults: { _controller: PersonalBundle:Default:projects }
    
game:
    path:   /game
    defaults: { _controller: PersonalBundle:Default:game }

gmail:
    path:   /gmail
    defaults: { _controller: PersonalBundle:Default:gmail }
    
facebook:
    path:   /example
    defaults: { _controller: PersonalBundle:Default:facebook }
    
picks:
    path:   /picks
    defaults: { _controller: PersonalBundle:Picks:index }

picks_login:
    path:   /picks/login
    defaults: { _controller: PersonalBundle:Picks:login }

picks_logout:
    path:   /picks/logout
    defaults: { _controller: PersonalBundle:Picks:logout }
    
menu:
    path:   /menu
    defaults: { _controller: PersonalBundle:Default:menu }

compiler:
    path:   /code
    defaults: { _controller: PersonalBundle:Code:code }

compiler_problem:
    path:   /code/p{problem}
    defaults: { _controller: PersonalBundle:Code:problem }

compiler_login:
    path:   /code/login
    defaults: { _controller: PersonalBundle:Code:login }

teacher_login:
    path:   /code/teacher
    defaults: { _controller: PersonalBundle:Code:login_teacher }

teacher_admin:
    path:   /teacher
    defaults: { _controller: PersonalBundle:Code:admin }

compiler_register:
    path:   /code/signup
    defaults: { _controller: PersonalBundle:Code:signup }
    
compiler_logout:
    path:   /code/logout
    defaults: { _controller: PersonalBundle:Code:logout }

student_signup:
    path:   /code/teacher/signup
    defaults: { _controller: PersonalBundle:Code:teacherRegister }

privacy:
    path:   /privacy
    defaults: { _controller: PersonalBundle:Default:privacy }
    
ajax_enroll:
    path:   /ajax/enroll
    defaults: { _controller: PersonalBundle:Ajax:addStudent }
    
ajax_progress:
    path:   /ajax/progress
    defaults: { _controller: PersonalBundle:Ajax:progress }