home:
    path:   /
    defaults: { _controller: PicksPickBundle:Default:index }
    
login:
    path:   /login
    defaults: { _controller: PicksPickBundle:Default:login }

logout:
    path:   /logout
    defaults: { _controller: PicksPickBundle:Default:logout }