Picks\PickBundle\Entity\Picks:
    type: entity
    table: picks
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        email:
            type: string
            nullable: true
            length: 256
            fixed: false
        choices:
            type: string
            nullable: true
            length: 256
            fixed: false
    lifecycleCallbacks: {  }
