Picks\PickBundle\Entity\Users:
    type: entity
    table: users
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: true
            length: 256
            fixed: false
        email:
            type: string
            nullable: true
            length: 256
            fixed: false
        password:
            type: string
            nullable: true
            length: 256
            fixed: false
        picked:
            type: integer
            nullable: true
            unsigned: false
            default: '0'
    lifecycleCallbacks: {  }
